version: "3.8"

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  api:
    container_name: api
    hostname: api
    restart: unless-stopped
    build:
      context: .
      dockerfile: api.Dockerfile
    env_file:
      - .env
    volumes:
      - static_data:/app/static
    expose:
      - 80
    ports:
      - "80:80"
    depends_on:
      - postgres
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn project.wsgi --bind 0.0.0.0:80 --reload"

volumes:
  static_data: {}
  postgres_data: {}